### ISSUE TITLE
Can't access documentation outside of US

### ISSUE THREAD

**Issue by jamesmoss** [hps/heartland-tokenization#16]
We're a UK development team working on an integration for a US client and it's impossible to access the developer documentation at https://developer.heartlandpaymentsystems.com/SecureSubmit/Documentation from an IP address outside the US.

What's the point of this? We have to use a VPN just to view the docs. It's incredibly frustrating and short-sighted.

**Comment by slogsdon** [comment]
Hi @jamesmoss! Sorry for the inconvenience here, but this is a restriction imposed by our security team. For both our developer portal and our certification/test environment, we can request your IP(s) be whitelisted to have proper access without a VPN, so if this is something you would like to pursue, send me an email at EntApp_DevPortal@e-hps.com to get that process started.

**Comment by jamesmoss** [comment]
That seems like a arbitrary restriction. What's the security risk for accessing documentation? Your security team is essentially promoting security through obscurity which is worrying for a payment provider.

Whitelisting isn't really useful - for the moment we'll continue to use a VPN.
