### ISSUE TITLE
hps.setText allows script injection

### ISSUE THREAD

**Issue by andreymir** [hps/heartland-tokenization#3]
Using hps.setText it is possible to replace the form inside the `<iframe>`:
```
hps.setText('heartland-cvv-label', '<script>alert("hello");</script>')
```

**Comment by slogsdon** [comment]
Thanks for the report, @andreymir! I'll definitely look into this more and update the code to minimize the risk.

On your end is the injected script being executed? In a quick test, I'm not seeing any script I inject into the `#heartland-body` element being executed.

**Comment by andreymir** [comment]
try this ;)

hps.setText('heartland-cvv-container', '<label for="heartland-cvv" id="heartland-cvv-label" style="font-size: 13px;text-transform: uppercase;font-weight: bold;display: block;width: 100%;clear: both;">CVV</label><input onclick="javascript:alert(\'ok\')" type="text" id="heartland-cvv" name="h-cvv" style="width: 309px;padding: 5px;font-size: 14px;margin: 3px 0px 15px 0px;border: 1px #ccc solid;background-image: -ms-linear-gradient(bottom, #F7F7F7 0%, #EFEFEF 100%);background-image: -moz-linear-gradient(bottom, #F7F7F7 0%, #EFEFEF 100%);background-image: -o-linear-gradient(bottom, #F7F7F7 0%, #EFEFEF 100%);background-image: -webkit-gradient(linear, left bottom, left top, color-stop(0, #F7F7F7), color-stop(1, #EFEFEF));background-image: -webkit-linear-gradient(bottom, #F7F7F7 0%, #EFEFEF 100%);background-image: linear-gradient(to top, #F7F7F7 0%, #EFEFEF 100%);width: 110px;">');

**Comment by slogsdon** [comment]
Yep, that does it. I was only testing with a basic script and hadn't yet tested with something that needed user interaction. I've started a fix for this over on #4

**Comment by slogsdon** [comment]
@andreymir We pushed out a fix for this: <https://hps.github.io/token/2.1/securesubmit.js>. Would you like to test this on your end?

**Comment by andreymir** [comment]
@slogsdon,  I'm getting the error `Uncaught TypeError: $form.SecureSubmit is not a function` on this code:
```JavaScript
            $(document).ready(function () {
                var $form = $('#payment_form');
                $form.SecureSubmit({
                    public_key: 'pkapi_cert_MrSafdEKB2dIHQEzDk',
                    type: 'iframe',
                    // target DOM node for iFrame placement
                    iframeTarget: '#securesubmit',
                    // target DOM node for submit button that
                    // initiates the tokenization process
                    buttonTarget: '#payment-submit',
                    onTokenSuccess: function (response) {
                        // callback for successful tokenization
                        $('#token_value').val(response.token_value);
                        $form.submit();
                    },
                    onTokenError: function (response) {
                        // callback on tokenization error
                        alert(response.message);
                    },
                });
            });
```

While with this script https://api.heartlandportico.com/SecureSubmit.v1/token/2.0/securesubmit.js is works fine.

**Comment by slogsdon** [comment]
@andreymir That error is due to this library being our pure Javascript implementation while the other file is from our jQuery based implementation ([hps/heartland-tokenization-jquery-library](https://github.com/hps/heartland-tokenization-jquery-library)). The pure Javascript implementation will be the primary library moving forward.

Here's a small update to your example that should work with this library:

```javascript
            $(document).ready(function () {
                var $form = $('#payment_form');
                new HPS({
                    publicKey: 'pkapi_cert_MrSafdEKB2dIHQEzDk',
                    type: 'iframe',
                    // target DOM node for iFrame placement
                    iframeTarget: '#securesubmit',
                    // target DOM node for submit button that
                    // initiates the tokenization process
                    buttonTarget: '#payment-submit',
                    onTokenSuccess: function (response) {
                        // callback for successful tokenization
                        $('#token_value').val(response.token_value);
                        $form.submit();
                    },
                    onTokenError: function (response) {
                        // callback on tokenization error
                        alert(response.message);
                    },
                });
            });
```
