### ISSUE TITLE
Distrusted SSL certificate on Chrome

### ISSUE THREAD

**Issue by rcubitto** [hps/heartland-tokenization#51]
When I include the script
```
<script src="https://api2.heartlandportico.com/SecureSubmit.v1/token/2.1/securesubmit.js"></script>
```

I get the following warning on Chrome 63

![image](https://user-images.githubusercontent.com/2274910/34522107-e3cb7140-f06f-11e7-948c-886c67a8e5ca.png)

According to these docs, on April 2018, the cert will be distrusted in Chrome. Any thoughts?

**Comment by slogsdon** [comment]
Hi @rcubitto!

Another team within the organization manages the servers where our resources are hosted, and yet another team manages the certificates associated with those endpoints. As far as I am aware, everything will be updated as needed before any cut-off dates and will be a seamless process for you as an integrator. This should also apply to other groups / resources within our organization.

**Comment by rcubitto** [comment]
Sounds good, thanks for the response.
