### ISSUE TITLE
Untrusted SSL Certificate - Mozilla/Google products

### ISSUE THREAD

**Issue by menudrive-mylesb** [hps/heartland-tokenization#57]
See #51, @slogsdon @russelleverett is there any way you can reach out to the ops team or whoever is in charge of this and have them get a certificate issued by someone other than Symantec? It is now untrusted by both Mozilla and Google in the latest versions of FF/Chrome.
See: https://www.ssllabs.com/ssltest/analyze.html?d=api2-c.heartlandportico.com

**Comment by slogsdon** [comment]
@menudrive-mylesb We have a ticket out to an internal team to get the certificate updated on api2-c.heartlandportico.com.

**Comment by menudrive-mylesb** [comment]
Thanks @slogsdon

**Comment by slogsdon** [comment]
@menudrive-mylesb Which version/URL of the library are you currently using? Version 2.2.1 (the latest), which uses the api2-c.heartlandportico.com domain, only updated the domain when compared [2.2.0](https://api2.heartlandportico.com/securesubmit.v1/token/2.2.0/securesubmit.js). Leveraging the 2.2.0 version of the library should side-step this issue while our teams get the certificate updated.

**Comment by menudrive-mylesb** [comment]
Using the latest (2.2.1), will give 2.2.0 a shot, thanks!

**Comment by slogsdon** [comment]
@menudrive-mylesb Thanks for the update!
